<?
$PERM["/"]["8"]="X";
$PERM["/"]["*"]="R";
$PERM["lichnyy-kabinet-prodavtsa"]["8"]="X";
$PERM["lichnyy-kabinet-prodavtsa"]["7"]="X";
$PERM["lichnyy-kabinet-prodavtsa"]["5"]="X";
$PERM["lichnyy-kabinet-prodavtsa"]["*"]="D";
$PERM["lichnyy-kabinet-pokupatelya"]["8"]="X";
$PERM["lichnyy-kabinet-pokupatelya"]["6"]="X";
$PERM["lichnyy-kabinet-pokupatelya"]["5"]="X";
$PERM["lichnyy-kabinet-pokupatelya"]["*"]="D";
$PERM["bitrix"]["2"]="D";
$PERM["bitrix"]["*"]="D";
?>