<?
$PERM["lichnyy-kabinet-pokupatelya"]["*"]="D";
$PERM["lichnyy-kabinet-pokupatelya"]["6"]="X";
$PERM["lichnyy-kabinet-pokupatelya"]["5"]="X";
$PERM["lichnyy-kabinet-prodavtsa"]["*"]="D";
$PERM["lichnyy-kabinet-prodavtsa"]["7"]="X";
$PERM["lichnyy-kabinet-prodavtsa"]["5"]="X";
$PERM["/"]["*"]="R";
?>