<?
$PERM["lichnyy-kabinet-prodavtsa"]["8"]="W";
$PERM["lichnyy-kabinet-prodavtsa"]["7"]="W";
$PERM["lichnyy-kabinet-prodavtsa"]["*"]="D";
$PERM["lichnyy-kabinet-pokupatelya"]["8"]="W";
$PERM["lichnyy-kabinet-pokupatelya"]["6"]="W";
$PERM["lichnyy-kabinet-pokupatelya"]["*"]="D";
$PERM["/"]["8"]="W";
$PERM["/"]["*"]="R";
$PERM["bitrix"]["2"]="D";
$PERM["bitrix"]["*"]="D";
?>